### ISSUE TITLE
Possible to remove Apple and Adobe updates from check?

### ISSUE THREAD

**Issue by magicMac1** [tmhoule/AppUpdates#5]
I was wondering if its possible to edit your check script to remove Apple and Adobe updates and only check for updates in the .plist?

**Comment by tmhoule** [comment]
Yes, you can comment out those sections of the script easily.  Edit the ScanForUpdates.sh script and comment out lines 251 (checkAppleUpdates), 259 (checkforAdobeUpdates) and optionally line 260 ($RUM --action=download).  I'll consider adding some type of preference in the future, but I expect that will not be a common request.
